import json
from pathlib import Path

import pandas as pd
import plotly.express as px
import streamlit as st

import alpaca_client
from nvda_backtest import BacktestResult, load_nvda_data
from nvda_strategy import NvdaStrategyConfig, add_indicators, generate_signals


def load_backtest_result_from_files(data_dir: str = "data", prefix: str = "nvda") -> BacktestResult | None:
    base = Path(data_dir)
    equity_path = base / f"{prefix}_equity_curve.csv"
    trades_path = base / f"{prefix}_trades.csv"
    stats_path = base / f"{prefix}_stats.json"

    if not (equity_path.exists() and trades_path.exists() and stats_path.exists()):
        return None

    equity_df = pd.read_csv(equity_path, index_col=0, parse_dates=True)

    # Handle empty trades file gracefully
    try:
        trades_df = pd.read_csv(trades_path)
    except pd.errors.EmptyDataError:
        trades_df = pd.DataFrame()

    with stats_path.open() as f:
        stats = json.load(f)

    return BacktestResult(equity_curve=equity_df["equity"], trades=trades_df, stats=stats)


def get_latest_signal() -> tuple[int, float] | None:
    """Return (desired_position, last_close) based on current NVDA data."""
    try:
        df = load_nvda_data("data/NVDA_alpdata.csv")
    except FileNotFoundError:
        return None
    cfg = NvdaStrategyConfig()
    df = add_indicators(df, cfg)
    df = generate_signals(df, cfg)
    latest = df.iloc[-1]
    return int(latest["position"]), float(latest["close"])


def main() -> None:
    st.title("NVDA Swing Strategy Dashboard")
    st.write("Backtest results, basic analytics, and current paper-trading status for NVDA.")

    # Live / paper-trading status
    st.subheader("Current NVDA Paper-Trading Status")
    col_a, col_b, col_c = st.columns(3)

    try:
        account = alpaca_client.get_account()
        nvda_pos = alpaca_client.get_nvda_position()
        desired = get_latest_signal()

        equity = float(account.equity)
        col_a.metric("Account Equity", f"${equity:,.2f}")

        if nvda_pos is not None:
            shares = float(nvda_pos.qty)
            avg_price = float(nvda_pos.avg_entry_price)
            col_b.metric("NVDA Shares", f"{shares:.0f}")
            col_c.metric("Avg Entry Price", f"${avg_price:.2f}")
        else:
            col_b.metric("NVDA Shares", "0")
            col_c.metric("Avg Entry Price", "—")

        if desired is not None:
            desired_pos, last_close = desired
            st.write(f"Latest strategy signal position: **{desired_pos}** (1 = long, 0 = flat), last close = ${last_close:.2f}")
        else:
            st.write("No NVDA data found to compute latest signal.")
    except Exception as e:  # noqa: BLE001
        st.warning(f"Could not load Alpaca account/position data: {e}")

    st.subheader("Backtest Results")
    result = load_backtest_result_from_files()
    if result is None:
        st.warning(
            "No NVDA backtest results found. "
            "Run the NVDA backtest first (e.g. `python -m app.nvda_backtest`) to generate data."
        )
        return

    st.subheader("Equity Curve")
    equity_df = result.equity_curve.to_frame("equity").reset_index()
    equity_df.columns = ["date", "equity"]

    fig = px.line(equity_df, x="date", y="equity", title="Equity Curve")
    fig.update_xaxes(title_text="Date", tickformat="%Y-%m")
    fig.update_yaxes(title_text="Equity")

    st.plotly_chart(fig, use_container_width=True)

    st.subheader("Summary Statistics")
    col1, col2, col3 = st.columns(3)
    total_return_pct = result.stats.get("total_return", 0.0) * 100
    max_dd_pct = result.stats.get("max_drawdown", 0.0) * 100
    win_rate_pct = result.stats.get("win_rate", 0.0) * 100

    col1.metric("Total Return", f"{total_return_pct:.1f}%")
    col2.metric("Max Drawdown", f"{max_dd_pct:.1f}%")
    col3.metric("Win Rate", f"{win_rate_pct:.1f}%")

    st.write(
        f"Trades: {result.stats.get('num_trades', 0)} | "
        f"Sharpe-like: {result.stats.get('sharpe_like', 0.0):.2f}"
    )

    st.subheader("Recent Trades")
    if not result.trades.empty:
        trades_display = result.trades.copy()
        for col in ("entry_time", "exit_time"):
            if col in trades_display.columns:
                trades_display[col] = pd.to_datetime(trades_display[col])
        st.dataframe(trades_display.tail(20))
    else:
        st.info("No trades were generated by the strategy.")

    st.subheader("Stock Price History (Data Folder)")

    # Discover available symbols from data files
    data_dir = Path("data")
    yf_files = sorted(data_dir.glob("*_yfdata.csv"))
    alp_files = sorted(data_dir.glob("*_alpdata.csv"))

    symbols = sorted({p.name.split("_")[0] for p in yf_files + alp_files})

    if not symbols:
        st.info("No *_yfdata.csv or *_alpdata.csv files found in the data folder.")
        return

    default_symbol = "NVDA" if "NVDA" in symbols else symbols[0]
    symbol = st.selectbox("Select symbol", symbols, index=symbols.index(default_symbol))

    col_yf, col_alp = st.columns(2)

    yf_path = data_dir / f"{symbol}_yfdata.csv"
    alp_path = data_dir / f"{symbol}_alpdata.csv"

    with col_yf:
        st.markdown(f"**{symbol} Price (yfinance data)**")
        if yf_path.exists():
            df_yf = pd.read_csv(yf_path, parse_dates=[0])
            df_yf = df_yf.rename(columns={df_yf.columns[0]: "date"})
            if "Close" in df_yf.columns:
                price_col = "Close"
            elif "close" in df_yf.columns:
                price_col = "close"
            else:
                price_col = df_yf.columns[1]

            fig_yf = px.line(df_yf, x="date", y=price_col, title=f"{symbol} (yfinance)")
            fig_yf.update_xaxes(title_text="Date", tickformat="%Y-%m")
            fig_yf.update_yaxes(title_text="Price")
            st.plotly_chart(fig_yf, use_container_width=True)
        else:
            st.info(f"No yfinance file found for {symbol} at {yf_path.name}.")

    with col_alp:
        st.markdown(f"**{symbol} Price (Alpaca data)**")
        if alp_path.exists():
            df_alp = pd.read_csv(alp_path)
            # Alpaca exports typically have a datetime column like 'timestamp' or unnamed index
            if "timestamp" in df_alp.columns:
                df_alp["date"] = pd.to_datetime(df_alp["timestamp"])
            elif "time" in df_alp.columns:
                df_alp["date"] = pd.to_datetime(df_alp["time"])
            else:
                # fall back to first column as date
                df_alp["date"] = pd.to_datetime(df_alp.iloc[:, 0])

            if "close" in df_alp.columns:
                price_col = "close"
            elif "Close" in df_alp.columns:
                price_col = "Close"
            else:
                # pick a reasonable numeric column if close not present
                numeric_cols = df_alp.select_dtypes(include="number").columns
                price_col = numeric_cols[0] if len(numeric_cols) > 0 else df_alp.columns[1]

            fig_alp = px.line(df_alp, x="date", y=price_col, title=f"{symbol} (Alpaca)")
            fig_alp.update_xaxes(title_text="Date", tickformat="%Y-%m")
            fig_alp.update_yaxes(title_text="Price")
            st.plotly_chart(fig_alp, use_container_width=True)
        else:
            st.info(f"No Alpaca file found for {symbol} at {alp_path.name}.")


if __name__ == "__main__":
    main()

